"""
Game State Classifier 결과를 받아서 death → respawn 구간을 찾음

killer_panel 또는 dead_or_killcam segment 발견
→ death segment로 등록
→ 이후 alive_playing 또는 respawned_playing segment 탐색
→ 일정 시간 이상 alive 상태가 유지되면 respawn으로 판정
→ notification_report의 death_killer_panel 이벤트와 cross-check

death_time:
KILLER 패널 또는 dead state가 시작되는 시점

respawn_time:
KILLER 패널이 사라지고 normal HUD / crosshair / weapon UI가 안정적으로 복귀한 시점
"""


from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Optional

import numpy as np


DEFAULT_RESPAWN_CONFIG: dict[str, Any] = {
    "death_states": ["killer_panel", "dead_or_killcam"],
    "alive_states": ["alive_playing", "respawned_playing"],
    "ignore_states_between_death_and_respawn": ["unknown", "menu_or_loading"],
    "thresholds": {
        "min_death_duration_sec": 0.5,
        "min_alive_after_respawn_sec": 0.5,
        "max_respawn_delay_sec": 8.0,
        "max_unknown_gap_sec": 1.2,
        "confirmed_confidence": 0.70,
        "inferred_confidence": 0.45,
        "notification_match_window_sec": 1.0,
    },
    "weights": {
        "death_segment": 0.35,
        "alive_segment": 0.35,
        "transition": 0.15,
        "notification_crosscheck": 0.15,
    },
}


@dataclass
class RespawnEvidence:
    death_state: str
    death_start_time: float
    death_end_time: float
    death_duration_sec: float
    death_confidence: float
    alive_state: Optional[str]
    alive_start_time: Optional[float]
    alive_end_time: Optional[float]
    alive_duration_sec: Optional[float]
    alive_confidence: Optional[float]
    respawn_delay_sec: Optional[float]
    matched_notification: Optional[dict[str, Any]] = None
    matched_game_state_event: Optional[dict[str, Any]] = None
    notes: list[str] = field(default_factory=list)


@dataclass
class RespawnEvent:
    event: str
    death_time: float
    respawn_time: Optional[float]
    confidence: float
    status: str
    source: list[str]
    evidence: RespawnEvidence
    result: str
    notes: list[str] = field(default_factory=list)


@dataclass
class DeathSegmentRecord:
    start_time: float
    end_time: float
    duration_sec: float
    state: str
    confidence: float
    status: str
    source: list[str]
    matched_notification: Optional[dict[str, Any]] = None
    notes: list[str] = field(default_factory=list)


@dataclass
class RespawnSegmentSummary:
    num_death_segments: int
    num_confirmed_respawns: int
    num_inferred_respawns: int
    num_missing_respawns: int
    num_uncertain: int
    first_death_time: Optional[float]
    first_respawn_time: Optional[float]


class RespawnSegmentDetector:
    """
    Detect death -> respawn segments from GameStateClassifier output.

    Input:
      - game_state_report.json generated by run_game_state_classifier.py
      - optional notification_report.json generated by run_notification_detector.py

    Output:
      - death segments
      - respawn events
      - missing/uncertain respawn cases

    MVP rule:
      A death segment starts when a stable state segment is killer_panel or
      dead_or_killcam. A respawn is confirmed when a later alive_playing or
      respawned_playing segment appears within max_respawn_delay_sec and remains
      stable for min_alive_after_respawn_sec or at least two sampled frames.
    """

    def __init__(self, config: Optional[dict[str, Any]] = None) -> None:
        cfg = json.loads(json.dumps(DEFAULT_RESPAWN_CONFIG))
        if config:
            for key, value in config.items():
                if isinstance(value, dict) and isinstance(cfg.get(key), dict):
                    cfg[key].update(value)
                else:
                    cfg[key] = value
        self.config = cfg
        self.death_states = set(cfg.get("death_states", []))
        self.alive_states = set(cfg.get("alive_states", []))
        self.ignore_states = set(cfg.get("ignore_states_between_death_and_respawn", []))
        self.thresholds = cfg.get("thresholds", {})
        self.weights = cfg.get("weights", {})

    @staticmethod
    def _clamp01(value: float) -> float:
        if value != value or value == float("inf") or value == float("-inf"):
            return 0.0
        return float(max(0.0, min(1.0, value)))

    @staticmethod
    def _duration_score(duration: float, required: float) -> float:
        if required <= 0:
            return 1.0
        return float(max(0.0, min(1.0, duration / required)))

    @staticmethod
    def _segment_duration(seg: dict[str, Any]) -> float:
        duration = seg.get("duration_sec")
        if duration is not None:
            return float(duration)
        return max(0.0, float(seg.get("end_time", 0.0)) - float(seg.get("start_time", 0.0)))

    @staticmethod
    def _segment_confidence(seg: dict[str, Any]) -> float:
        return float(seg.get("confidence", 0.0) or 0.0)

    @staticmethod
    def _event_time(event: dict[str, Any]) -> float:
        return float(event.get("time", event.get("start_time", event.get("timestamp_sec", 0.0))) or 0.0)

    def _matching_death_notification(
        self,
        death_segment: dict[str, Any],
        notification_events: list[dict[str, Any]],
    ) -> Optional[dict[str, Any]]:
        window = float(self.thresholds.get("notification_match_window_sec", 1.0))
        start_t = float(death_segment.get("start_time", 0.0))
        end_t = float(death_segment.get("end_time", start_t))
        candidates: list[tuple[float, dict[str, Any]]] = []
        for ev in notification_events:
            ev_name = str(ev.get("event", ""))
            cls = str(ev.get("class_name", ev.get("top_class", "")))
            if ev_name not in {"death_notification"} and cls not in {"death_killer_panel"}:
                continue
            t = self._event_time(ev)
            if start_t - window <= t <= end_t + window:
                # Prefer events close to the start of death state and high confidence.
                distance = abs(t - start_t)
                conf = float(ev.get("confidence", ev.get("top_confidence", 0.0)) or 0.0)
                candidates.append((distance - conf * 0.1, ev))
        if not candidates:
            return None
        candidates.sort(key=lambda item: item[0])
        return candidates[0][1]

    def _matching_game_state_event(
        self,
        death_segment: dict[str, Any],
        game_state_events: list[dict[str, Any]],
        target_events: set[str],
    ) -> Optional[dict[str, Any]]:
        window = float(self.thresholds.get("notification_match_window_sec", 1.0))
        start_t = float(death_segment.get("start_time", 0.0))
        end_t = float(death_segment.get("end_time", start_t))
        candidates: list[tuple[float, dict[str, Any]]] = []
        for ev in game_state_events:
            if str(ev.get("event", "")) not in target_events:
                continue
            t = self._event_time(ev)
            if start_t - window <= t <= end_t + window:
                candidates.append((abs(t - start_t), ev))
        if not candidates:
            return None
        candidates.sort(key=lambda item: item[0])
        return candidates[0][1]

    def _find_respawn_segment(self, death_idx: int, segments: list[dict[str, Any]]) -> tuple[Optional[dict[str, Any]], list[str]]:
        notes: list[str] = []
        death_seg = segments[death_idx]
        death_end = float(death_seg.get("end_time", death_seg.get("start_time", 0.0)))
        max_delay = float(self.thresholds.get("max_respawn_delay_sec", 8.0))
        max_unknown_gap = float(self.thresholds.get("max_unknown_gap_sec", 1.2))

        last_seen_t = death_end
        for later in segments[death_idx + 1:]:
            later_start = float(later.get("start_time", 0.0))
            later_end = float(later.get("end_time", later_start))
            state = str(later.get("state", "unknown"))

            if later_start - death_end > max_delay:
                notes.append(f"max_respawn_delay_exceeded:{later_start - death_end:.3f}>{max_delay:.3f}")
                return None, notes

            gap = max(0.0, later_start - last_seen_t)
            if state not in self.ignore_states and gap > max_unknown_gap:
                notes.append(f"large_gap_before_candidate:{gap:.3f}>{max_unknown_gap:.3f}")

            if state in self.death_states:
                # Still dead/killcam; extend search origin but keep original death segment.
                last_seen_t = later_end
                continue

            if state in self.alive_states:
                return later, notes

            if state in self.ignore_states:
                last_seen_t = later_end
                continue

            # Other non-alive states are not necessarily fatal, but mark uncertainty.
            notes.append(f"intermediate_state:{state}@{later_start:.3f}")
            last_seen_t = later_end

        notes.append("no_later_segment")
        return None, notes

    def _confidence(
        self,
        death_seg: dict[str, Any],
        alive_seg: Optional[dict[str, Any]],
        matched_notification: Optional[dict[str, Any]],
        matched_state_event: Optional[dict[str, Any]],
    ) -> float:
        min_death_duration = float(self.thresholds.get("min_death_duration_sec", 0.5))
        min_alive_duration = float(self.thresholds.get("min_alive_after_respawn_sec", 0.5))
        death_duration = self._segment_duration(death_seg)
        death_conf = self._segment_confidence(death_seg)
        death_score = self._clamp01(0.55 * death_conf + 0.45 * self._duration_score(death_duration, min_death_duration))

        if alive_seg is None:
            alive_score = 0.0
        else:
            alive_duration = self._segment_duration(alive_seg)
            alive_conf = self._segment_confidence(alive_seg)
            frame_count = int(alive_seg.get("frame_count", 0) or 0)
            frame_bonus = 1.0 if frame_count >= 2 else 0.65
            alive_score = self._clamp01(0.55 * alive_conf + 0.30 * self._duration_score(alive_duration, min_alive_duration) + 0.15 * frame_bonus)

        transition_score = 0.0
        if alive_seg is not None:
            death_end = float(death_seg.get("end_time", death_seg.get("start_time", 0.0)))
            alive_start = float(alive_seg.get("start_time", 0.0))
            max_delay = float(self.thresholds.get("max_respawn_delay_sec", 8.0))
            delay = max(0.0, alive_start - death_end)
            transition_score = self._clamp01(1.0 - delay / max(max_delay, 1e-6) * 0.5)
            if matched_state_event:
                transition_score = max(transition_score, float(matched_state_event.get("confidence", 0.0) or 0.0))

        notification_score = 0.0
        if matched_notification:
            notification_score = float(matched_notification.get("confidence", matched_notification.get("top_confidence", 0.0)) or 0.0)

        conf = (
            float(self.weights.get("death_segment", 0.35)) * death_score
            + float(self.weights.get("alive_segment", 0.35)) * alive_score
            + float(self.weights.get("transition", 0.15)) * transition_score
            + float(self.weights.get("notification_crosscheck", 0.15)) * notification_score
        )
        return self._clamp01(conf)

    def _status_and_result(self, confidence: float, alive_seg: Optional[dict[str, Any]], notes: list[str]) -> tuple[str, str]:
        confirmed = float(self.thresholds.get("confirmed_confidence", 0.70))
        inferred = float(self.thresholds.get("inferred_confidence", 0.45))
        if alive_seg is None:
            if "no_later_segment" in notes:
                return "UNCERTAIN", "RESPAWN_UNOBSERVED_VIDEO_END"
            if confidence >= inferred:
                return "UNCERTAIN", "MISSING_OR_UNOBSERVED_RESPAWN"
            return "MISSING", "MISSING_RESPAWN"
        if confidence >= confirmed:
            return "CONFIRMED", "RESPAWN_DETECTED"
        if confidence >= inferred:
            return "INFERRED", "RESPAWN_DETECTED_LOW_CONFIDENCE"
        notes.append(f"confidence_below_inferred:{confidence:.3f}<{inferred:.3f}")
        return "UNCERTAIN", "RESPAWN_UNCERTAIN"

    def detect(
        self,
        game_state_report: dict[str, Any],
        notification_report: Optional[dict[str, Any]] = None,
    ) -> dict[str, Any]:
        temporal = game_state_report.get("temporal_aggregation", {})
        segments = list(temporal.get("segments", []))
        game_state_events = list(temporal.get("events", []))
        notification_events = list((notification_report or {}).get("temporal_aggregation", {}).get("events", []))

        # Stable sort and sanitize.
        segments = sorted(segments, key=lambda s: (float(s.get("start_time", 0.0)), float(s.get("end_time", 0.0))))

        death_records: list[DeathSegmentRecord] = []
        respawn_events: list[RespawnEvent] = []
        used_alive_segment_indices: set[int] = set()

        for idx, seg in enumerate(segments):
            state = str(seg.get("state", "unknown"))
            if state not in self.death_states:
                continue

            death_duration = self._segment_duration(seg)
            death_conf = self._segment_confidence(seg)
            min_death_duration = float(self.thresholds.get("min_death_duration_sec", 0.5))
            notes: list[str] = []
            if death_duration < min_death_duration:
                notes.append(f"short_death_segment:{death_duration:.3f}<{min_death_duration:.3f}")

            matched_notification = self._matching_death_notification(seg, notification_events)
            matched_death_state_event = self._matching_game_state_event(seg, game_state_events, {"death_state_entered"})

            if death_duration < min_death_duration and not matched_notification:
                death_records.append(
                    DeathSegmentRecord(
                        start_time=float(seg.get("start_time", 0.0)),
                        end_time=float(seg.get("end_time", seg.get("start_time", 0.0))),
                        duration_sec=death_duration,
                        state=state,
                        confidence=death_conf,
                        status="FILTERED_SHORT_SEGMENT",
                        source=["game_state_segment"],
                        matched_notification=None,
                        notes=notes.copy() + ["not_promoted_to_respawn_event"],
                    )
                )
                continue

            death_record_status = "CONFIRMED" if matched_notification or (state == "killer_panel" and death_conf >= 0.60) else "INFERRED"
            death_records.append(
                DeathSegmentRecord(
                    start_time=float(seg.get("start_time", 0.0)),
                    end_time=float(seg.get("end_time", seg.get("start_time", 0.0))),
                    duration_sec=death_duration,
                    state=state,
                    confidence=death_conf,
                    status=death_record_status,
                    source=["game_state_segment"] + (["death_notification_crosscheck"] if matched_notification else []),
                    matched_notification=matched_notification,
                    notes=notes.copy(),
                )
            )

            alive_seg, search_notes = self._find_respawn_segment(idx, segments)
            notes.extend(search_notes)
            alive_idx = segments.index(alive_seg) if alive_seg in segments else -1
            if alive_idx in used_alive_segment_indices:
                notes.append("alive_segment_already_used_by_previous_death")
                continue
            if alive_idx >= 0:
                used_alive_segment_indices.add(alive_idx)

            matched_respawn_state_event = None
            if alive_seg is not None:
                matched_respawn_state_event = self._matching_game_state_event(alive_seg, game_state_events, {"respawn_candidate", "respawned_playing"})

            confidence = self._confidence(seg, alive_seg, matched_notification, matched_respawn_state_event)
            status, result = self._status_and_result(confidence, alive_seg, notes)

            if alive_seg is None:
                alive_state = None
                alive_start = None
                alive_end = None
                alive_duration = None
                alive_conf = None
                respawn_delay = None
                respawn_time = None
            else:
                alive_state = str(alive_seg.get("state", "unknown"))
                alive_start = float(alive_seg.get("start_time", 0.0))
                alive_end = float(alive_seg.get("end_time", alive_start))
                alive_duration = self._segment_duration(alive_seg)
                alive_conf = self._segment_confidence(alive_seg)
                death_end = float(seg.get("end_time", seg.get("start_time", 0.0)))
                respawn_delay = max(0.0, alive_start - death_end)
                respawn_time = alive_start

            evidence = RespawnEvidence(
                death_state=state,
                death_start_time=float(seg.get("start_time", 0.0)),
                death_end_time=float(seg.get("end_time", seg.get("start_time", 0.0))),
                death_duration_sec=death_duration,
                death_confidence=death_conf,
                alive_state=alive_state,
                alive_start_time=alive_start,
                alive_end_time=alive_end,
                alive_duration_sec=alive_duration,
                alive_confidence=alive_conf,
                respawn_delay_sec=respawn_delay,
                matched_notification=matched_notification,
                matched_game_state_event=matched_respawn_state_event or matched_death_state_event,
                notes=notes,
            )

            source = ["game_state_segments"]
            if matched_notification:
                source.append("death_notification_crosscheck")
            if matched_respawn_state_event:
                source.append("respawn_state_event_crosscheck")
            if alive_seg is not None:
                source.append("alive_hud_returned")

            respawn_events.append(
                RespawnEvent(
                    event="respawn_segment",
                    death_time=float(seg.get("start_time", 0.0)),
                    respawn_time=respawn_time,
                    confidence=confidence,
                    status=status,
                    source=source,
                    evidence=evidence,
                    result=result,
                    notes=notes.copy(),
                )
            )

        confirmed = [e for e in respawn_events if e.status == "CONFIRMED"]
        inferred = [e for e in respawn_events if e.status == "INFERRED"]
        missing = [e for e in respawn_events if e.status == "MISSING"]
        uncertain = [e for e in respawn_events if e.status == "UNCERTAIN"]
        first_respawn = next((e.respawn_time for e in respawn_events if e.respawn_time is not None), None)
        summary = RespawnSegmentSummary(
            num_death_segments=len(death_records),
            num_confirmed_respawns=len(confirmed),
            num_inferred_respawns=len(inferred),
            num_missing_respawns=len(missing),
            num_uncertain=len(uncertain),
            first_death_time=death_records[0].start_time if death_records else None,
            first_respawn_time=first_respawn,
        )

        return {
            "config": self.config,
            "summary": asdict(summary),
            "death_segments": [asdict(d) for d in death_records],
            "respawn_events": [asdict(e) for e in respawn_events],
            "source_stats": {
                "num_game_state_segments": len(segments),
                "num_game_state_events": len(game_state_events),
                "num_notification_events": len(notification_events),
            },
        }


def load_respawn_config(config_path: Optional[str | Path]) -> dict[str, Any]:
    cfg = json.loads(json.dumps(DEFAULT_RESPAWN_CONFIG))
    if not config_path:
        return cfg
    with Path(config_path).open("r", encoding="utf-8") as f:
        user_cfg = json.load(f)
    for key, value in user_cfg.items():
        if isinstance(value, dict) and isinstance(cfg.get(key), dict):
            cfg[key].update(value)
        else:
            cfg[key] = value
    return cfg


def load_json(path: str | Path) -> dict[str, Any]:
    with Path(path).open("r", encoding="utf-8") as f:
        return json.load(f)
